common:
  cameras: [ front ]
  # full cameras: [front,left_shoulder,right_shoulder,wrist]     [ front ]
  camera_resolution: [ 128, 128 ]
  #  [ 128, 128 ] [ 256, 256 ]
  scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
  continue_path: None

ddp:
    master_addr: "localhost"
    master_port: "29501"
    num_devices: 2
    device_id: 0

rlbench:
    task_name: "multi-tasks robot manipulation"
    # change the task as you want. in our paper, we select these 10 tasks.
    tasks: [close_jar,open_drawer,sweep_to_dustpan_of_size,meat_off_grill,turn_tap,slide_block_to_color_target,put_item_in_drawer,reach_and_drag,push_buttons,stack_blocks]
    # you could try more/fewer demos.
    demos: 20
    # you could try more/fewer views.
    num_view_for_nerf: 20
    demo_path: /my/demo/path      # will be removed by "${cur_dir}/data/train_data"
    episode_length: 20
    # full cameras: [front,left_shoulder,right_shoulder,wrist]
    cameras: ${common.cameras}
    camera_resolution: ${common.camera_resolution}
    scene_bounds: ${common.scene_bounds}
    include_lang_goal_in_obs: True
    headless: True

replay:
    batch_size: 1
    timesteps: 1
    prioritisation: False
    only_next_keypose: ${common.only_next_keypose}
    task_uniform: True # uniform sampling of tasks for multi-task buffers
    use_disk: True
    path: '/tmp/arm/replay' # only used when use_disk is True.
    max_parallel_processes: 16

evaluation: # for online evaluation
    eval_freq: 10000
    eval_episodes: 25
    time_in_state: True
    record_every_n: 10000
    episode_length: 20  # default
    # episode_length: 25
    gpu: 0


framework:
    use_online_evaluation: False
    log_freq: 10
    save_freq: 10000
    train_envs: 1
    replay_ratio: ${replay.batch_size}
    transitions_before_train: 200
    tensorboard_logging: False
    csv_logging: True
    training_iterations: 300010
    gpu: 0
    env_gpu: 0
    log_dir: "logs/"
    logging_level: 20 
    seeds: 1
    start_seed: 0
    load_existing_weights: False
    num_weights_to_keep: 60 # older checkpoints will be deleted chronologically
    num_workers: 0
    record_every_n: 5
    # wandb setting
    use_wandb: False
    wandb_project: "123"
    wandb_group: "456"
    seed: 0
    wandb_name: "789"
    tqdm_mininterval: 10    # tqdm print interval (s)


defaults:
    - method: Splat-Actor_BC

hydra:
    run:
        dir: ${framework.log_dir}/logs
